services:
  - type: web
    name: gymfeed-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: GymFeed
      - key: FRONTEND_URL
        sync: false
